server:
  port: 8091

spring:
  application:
    name: HugeConfigCenter
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mzbank/config
          username: mzbank
          password: at2016year
          default-label: master
          search-paths: config-client
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8090/eureka

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
