server:
  port: 8080

spring:
  application:
    name: HugeBusinessManager
  datasource:
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@localhost:1521:orcl
#    username: MZBANK
#    password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/jpa
      username: root
      password: 123456

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

#    oracle
#      mysql
#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8090/eureka

#mybatis打印日志
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: HugeBusinessManager.BusinessManagerPojo
  mapper-locations: classpath:/mapper/*.xml
